#1505 Restrict IA upload to Word files only
jac-uk/jac-kit pull request #37
Opened 2021-10-15 09:52 UTC by mbrookeswebdev

Users should be able to upload only .doc/.docx files for IAs on the Exercise Downloads page:

![Screenshot 2021-10-15 at 10 46 15](https://user-images.githubusercontent.com/40855898/137468703-fc8c2e09-f5bf-4d0a-9c74-db2603294174.png)

Other downloads should not be affected:

![Screenshot 2021-10-15 at 10 45 24](https://user-images.githubusercontent.com/40855898/137468678-1aa7ff8c-96db-4c2c-8ee0-0a5bb5cdd441.png)

2021-11-03 13:50 UTC, warrensearle requested changes

2021-11-03 13:50 UTC, warrensearle commented on src/packages/draftComponents/Form/FileUpload.vue
> +    },
Hey @mbrookeswebdev I agree with @HalcyonJAC comment below. Can we change this prop to be `types`, say, which accepts a CSV string of extensions. Something like the following should do the trick:
```
types: {
  type: String,
  required: false,
  default: '.pdf,.docx,.doc,.odt,.txt,.fodt'
}
```
As a follow on task we should also consider checking mime type.

2021-11-04 09:11 UTC, mbrookeswebdev commented on src/packages/draftComponents/Form/FileUpload.vue
> +    },
I experimented with changing the mime type of a file and the browser accepted it, so I think if mime types to be checked, it needs to be done at the back end. Do we need to go that far, given that up to now there was a couple of occasions the staff uploaded the wrong file?

2021-11-04 09:12 UTC, mbrookeswebdev commented on src/packages/draftComponents/Form/FileUpload.vue
> +    fileExtensions() {
I've made changes as requested.

2021-11-04 13:40 UTC, HalcyonJAC commented on src/packages/draftComponents/Form/FileUpload.vue
> +    },
@mbrookeswebdev I think this is OK, mime types might be worthwhile if this turns into a problem or if it needs to be a specific type.

2021-11-04 13:40 UTC, HalcyonJAC approved these changes

2021-11-05 14:11 UTC, tomlovesgithub approved these changes

2021-11-05 14:23 UTC, warrensearle approved these changes
👍

2021-11-05 14:38 UTC, merged