Email validation
jac-uk/jac-kit pull request #55
Opened 2022-03-09 17:13 UTC by tomlovesgithub

2022-04-05 16:28 UTC, warrensearle requested changes
See comment

2022-04-05 16:28 UTC, warrensearle commented on src/packages/draftComponents/Form/FormField.vue
> -        if (this.minDate && value) {
@tomlovesgithub should we be removing this code? Looks like it might be used by date input field, please check 😄

2022-04-08 15:36 UTC, warrensearle commented
>ive made the changes but i defo didnt remove that code [purposefully] this has knocked my confidence with the PR a bit! 😅

Ok @tomlovesgithub let me know when you'd like this reviewed again

2022-04-12 11:28 UTC, tomlovesgithub commented
> > ive made the changes but i defo didnt remove that code [purposefully] this has knocked my confidence with the PR a bit! 😅
> 
> Ok @tomlovesgithub let me know when you'd like this reviewed again

Think it was just an issue with where the PR was based off - happy for rereview now!

2022-05-05 14:59 UTC, warrensearle approved these changes
👍

2022-05-05 14:59 UTC, merged

2022-05-31 12:33 UTC, andrew-isaac commented
@tomlovesgithub  - Can you give me an update on what is happening with this work?