added pagination to bottom of table
jac-uk/jac-kit pull request #57
Opened 2022-03-23 15:15 UTC by HalcyonJAC

At the bottom of Table it is paginated via `Previous` and `Next`. Add for example, `A, B, C, D, ...` or `1, 2, 3, 4, ...` between `Previous` and `Next`.

2022-04-07 08:10 UTC, tomlovesgithub approved these changes
This is a humdinger! been winding users up for some time - great work!

2022-04-08 09:35 UTC, warrensearle requested changes
This is looking good, just a couple of points to go through

2022-04-08 09:35 UTC, warrensearle commented on src/packages/components/Table/tableAsyncQuery.js
> +      total = await getTotal(queryRef); // retrieve total number of data if required
Hey @HalcyonJAC let's talk through this. It's looking good however just want to understand what we're achieving here

2022-04-13 09:16 UTC, HalcyonJAC commented on src/packages/components/Table/tableAsyncQuery.js
> +      total = await getTotal(queryRef); // retrieve total number of data if required
I've moved `tableAsyncQuery` into`tableQuery.js` so that we don't need to maintain two query logics.

2022-04-13 09:52 UTC, warrensearle approved these changes
Thanks @HalcyonJAC this is looking good 👍

2022-04-19 12:34 UTC, merged