Separate whitespace validation block
jac-uk/jac-kit pull request #75
Opened 2022-09-02 13:25 UTC by tomlovesgithub

Seems the last Pr wasn't sufficient
... 
This should avoid errors and still allow for the validation to work

2022-09-15 11:46 UTC, HalcyonJAC approved these changes

2022-09-15 14:55 UTC, warrensearle requested changes
hmmm... not sure about this change. Can we have a quick chat to walk through the desired logic?

 - The validation now fires whether or not `this.required` is `true`
 - _Perhaps_ could be simplified into one line rather than duplicating code:
 ```
 ... || (typeof value === 'string' && value.replace(...).length === 0) 
 ```

2022-10-10 08:41 UTC, warrensearle requested changes
At the moment you have
``` 
if (this.required && (value === null || value === undefined || value.length === 0) || (typeof value === 'string' && value.replace(/\s/g, '').length === 0) ) { 
```
should this be:
``` 
if (this.required && (value === null || value === undefined || value.length === 0 || (typeof value === 'string' && value.replace(/\s/g, '').length === 0)) ) { 
```

2022-10-26 11:09 UTC, warrensearle approved these changes

2022-10-26 11:10 UTC, merged