Add qualification constants and filters
jac-uk/jac-kit pull request #77
Opened 2022-10-11 14:03 UTC by HalcyonJAC

2022-10-12 15:25 UTC, warrensearle requested changes
Lets make the underlying data that's stored in the database as well as the names of our constants a little more relevant / semantic. I know it's difficult bet lets try. @HalcyonJAC @andrew-isaac @tomlovesgithub

2022-10-28 09:01 UTC, tomlovesgithub commented on src/packages/filters/filters.js
> +    lookup[NOT_COMPLETE_PUPILLAGE_REASONS.OPTION_1] = 'Qualified solicitor, qualified lawyer from another jurisdiction, or a legal academic transferred to the Bar';
`transferred`
`called-pre-2002`
`other`

2022-10-28 09:03 UTC, tomlovesgithub commented on src/packages/helpers/constants.js
> +  OPTION_1: 'reason-not-completed-pupillage-1',
same as above here

2022-11-02 09:28 UTC, warrensearle approved these changes
Great, much better. Thanks @HalcyonJAC 👍

2022-11-02 13:40 UTC, tomlovesgithub approved these changes

2022-11-07 17:27 UTC, merged